# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- develop

pool:
  vmImage: 'windows-latest'

variables:
  GitVersion.FullSemVer: ''

steps:
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'
  name: GitVersionSetup
  displayName: 'get gitversion tools'
  
- task: gitversion/execute@0
  name: GetVersion
  displayName: 'get version from repository'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    verbosityRestore: Normal
    feedsToUse: config
    includeNuGetOrg: true

# tests
- task: DotNetCoreCLI@2
  displayName: 'build tests'
  inputs:
    command: 'build'
    projects: '**/*.Tests.csproj'

- task: VSTest@2
  displayName: 'run tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*.Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
      !**\ref\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

# Nuget package
- task: DotNetCoreCLI@2
  displayName: 'pack project'
  inputs:
    command: 'pack'
    packagesToPack: 'Capsaicin.RegexUtil/Capsaicin.RegexUtil.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitVersion.FullSemVer'